In [1]:
# Install package
%pip install --upgrade git+git://github.com/rahulspsec/portfoliotools.git

Collecting git+git://github.com/rahulspsec/portfoliotools.git
  Cloning git://github.com/rahulspsec/portfoliotools.git to /private/var/folders/5g/y08h4ccx7419m412xm4k361c0000gn/T/pip-req-build-t0c74fts
  Running command git clone -q git://github.com/rahulspsec/portfoliotools.git /private/var/folders/5g/y08h4ccx7419m412xm4k361c0000gn/T/pip-req-build-t0c74fts
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from portfoliotools==0.0.1) (4.8.1)
Requirement already satisfied, skipping upgrade: pandas in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from portfoliotools==0.0.1) (0.25.1)
Requirement already satisfied, skipping upgrade: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from portfoliotools==0.0.1) (1.17.1)
Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from beautifulsoup4->portfoliotools==0.0.1) (1.9.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->portfoliotools==0.0.1) (2.8.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->portfoliotools==0.0.1) (2019.2)
Requirement already satisfied, skipping upgrade: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->portfoliotools==0.0.1) (1.12.0)
Installing collected packages: portfoliotools
  Found existing installation: portfoliotools 0.0.1
    Uninstalling portfoliotools-0.0.1:
      Successfully uninstalled portfoliotools-0.0.1
  Running setup.py install for portfoliotools ... done
Successfully installed portfoliotools-0.0.1
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [44]:
from screener.stock_detail import StockDetail
import pandas as pd
pd.options.display.max_columns = None

In [45]:
stock = StockDetail("INFY")
print(stock.details())

ERROR:root:'LTDebt'
ERROR:root:Error calculating derived info INFY

{'Overview': {'Info': {'Stock Name': 'INFY', 'Date': '05Mar20', 'Last Close': 758.75, 'Last COB': '04Mar20', 'Average Volume': 8714828.52, 'Standard Deviation': 16.4, 'CAGR': 16.24, 'Annual Volatility': 26.73, 'Sharpe': 0.476, 'Sortino': 0.558}, '52W Statistics': {'52W High': 847.0, '52W Low': 615.1, 'Price% 52 Week': 61.94, 'Price per Range': '60% to 70%'}, 'Returns': {'Return 1D': 2.39, 'Return 1W': -4.97, 'Return 1M': -2.81, 'Return 1Y': 0.52}}, 'Technical Analytics': {'WilliamsR': {'Smoothing Period': 5, 'Lookback Period': 12, '%R': -59.02, '%D': -74.93, 'WilliamR Signal': ''}, 'Moving Average': {'30D Moving Average': 778.94, '60D Moving Average': 757.68, '200D Moving Average': 753.25, '12D Exponential Moving Average': 770.97, '26D Exponential Moving Average': 773.15}, 'MacD': {'MACD Line': -2.17, 'MACD Indicator': 6.08, 'MACD Line to Indicator Diff (Value)': -8.25, 'MACD Line to Indicator Diff (Days)': -5, 'MACD Line to Indicator Diff Rolling Peak': 8.47, 'MACD Line to Indicator Diff Rolling Peak per': -97.44, 'MACD Signal': 'BUY'}, 'Bollinger Band': {'Bollinger Band Upper': 817.89, 'Bollinger Band Middle': 770.97, 'Bollinger Band Lower': 724.06}, 'RSI': {'RSI Value': 43.42, 'RSI Signal': ''}, 'ATR': {'ATR Value': 19.42}, 'ADX': {'ADX Value': 27.06}, 'OBV': {'OBV Value': 484255115.0, 'OBV Index': 55.57, 'OBV Slope': -0.87, 'OBV Signal': ''}, 'Slope': {'Slope Value': -83.27}, 'Renko': {'Renko Trend': 'DOWN', 'Renko Strength': -2, 'Renko Signal': '', 'Renko Date': '2020-02-28'}}, 'Fundamental Analytics': {'EarningYield': -999, 'FCFYield': -999, 'ROC': -999, 'BookToMkt': -999, 'DivYield': 0.0216}}

In [52]:
from screener.stock_screener import StockScreener
a = StockScreener(['INFY', 'SBI'])
display(a.get_summary())

ERROR:root:'LTDebt'
ERROR:root:Error calculating derived info INFY
ERROR:root:'D&A'
ERROR:root:Error calculating derived info SBI

,Stock Name,Date,Last Close,Last COB,Average Volume,Standard Deviation,CAGR,Annual Volatility,Sharpe,Sortino,52W High,52W Low,Price% 52 Week,Price per Range,Return 1D,Return 1W,Return 1M,Return 1Y,Smoothing Period,Lookback Period,%R,%D,WilliamR Signal,30D Moving Average,60D Moving Average,200D Moving Average,12D Exponential Moving Average,26D Exponential Moving Average,MACD Line,MACD Indicator,MACD Line to Indicator Diff (Value),MACD Line to Indicator Diff (Days),MACD Line to Indicator Diff Rolling Peak,MACD Line to Indicator Diff Rolling Peak per,MACD Signal,Bollinger Band Upper,Bollinger Band Middle,Bollinger Band Lower,RSI Value,RSI Signal,ATR Value,ADX Value,OBV Value,OBV Index,OBV Slope,OBV Signal,Slope Value,Renko Trend,Renko Strength,Renko Signal,Renko Date,EarningYield,FCFYield,ROC,BookToMkt,DivYield,Sector
0,INFY,05Mar20,758.75,04Mar20,8714828.52,16.40,16.24,26.73,0.476,0.558,847.00,615.10,61.94,60% to 70%,2.39,-4.97,-2.81,0.52,5,12,-59.02,-74.93,,778.94,757.68,753.25,770.97,773.15,-2.17,6.08,-8.25,-5,8.47,-97.44,BUY,817.89,770.97,724.06,43.42,,19.42,27.06,484255115.0,55.57,-0.87,,-83.27,DOWN,-2,,2020-02-28,-999,-999,-999,-999,0.0216,
1,SBI,05Mar20,9.47,04Mar20,39839.55,0.07,4.91,7.36,0.192,0.288,9.77,8.68,72.48,70% to 80%,0.42,-1.46,0.00,8.98,5,14,-42.55,-66.33,,9.50,9.35,9.18,9.46,9.46,0.00,0.03,-0.03,-5,0.04,-76.41,,9.67,9.47,9.27,50.74,,0.11,24.38,265005.0,6.65,-0.99,,1.60,DOWN,-1,,2020-02-28,-999,-999,-999,-999,0.0303,

In [47]:
from screener.screener_pattern import CandleStickPatters

In [48]:
a = CandleStickPatters(stock.historical_prices)

In [49]:
display(a.get_bullish_patters())
display(a.get_bearish_patters())

,high,low,open,close,volume,adj close,Dragon Fly Doji,Slope
Date,,,,,,,,
2018-04-05,575.650024,564.549988,569.775024,573.775024,7763544.0,529.379822,,0.000000
2018-04-06,573.000000,561.049988,571.500000,563.500000,5937742.0,519.899902,,0.000000
2018-04-09,562.900024,553.275024,562.500000,555.625000,7202882.0,512.634216,,0.000000
2018-04-10,562.250000,552.700012,556.000000,556.700012,8926058.0,513.626038,,0.000000
2018-04-11,565.750000,558.250000,559.000000,562.125000,9025574.0,518.631226,,-71.622196
...,...,...,...,...,...,...,...,...
2020-02-26,801.450012,780.500000,793.950012,782.750000,8760569.0,782.750000,,-73.610460
2020-02-27,780.750000,772.200012,778.000000,777.849976,5223386.0,777.849976,,-78.990497
2020-02-28,756.799988,722.049988,750.000000,731.700012,14123957.0,731.700012,,-86.156545
2020-03-02,765.900024,733.750000,737.000000,741.049988,9821523.0,741.049988,,-86.547427
2020-03-04,761.500000,745.549988,753.900024,758.750000,11012895.0,758.750000,,-83.274482

,high,low,open,close,volume,adj close,Three Black Crow,Gravestone Doji,Slope
Date,,,,,,,,,
2018-04-05,575.650024,564.549988,569.775024,573.775024,7763544.0,529.379822,,,0.000000
2018-04-06,573.000000,561.049988,571.500000,563.500000,5937742.0,519.899902,,,0.000000
2018-04-09,562.900024,553.275024,562.500000,555.625000,7202882.0,512.634216,,,0.000000
2018-04-10,562.250000,552.700012,556.000000,556.700012,8926058.0,513.626038,,,0.000000
2018-04-11,565.750000,558.250000,559.000000,562.125000,9025574.0,518.631226,,,-71.622196
...,...,...,...,...,...,...,...,...,...
2020-02-26,801.450012,780.500000,793.950012,782.750000,8760569.0,782.750000,,,-73.610460
2020-02-27,780.750000,772.200012,778.000000,777.849976,5223386.0,777.849976,,,-78.990497
2020-02-28,756.799988,722.049988,750.000000,731.700012,14123957.0,731.700012,,,-86.156545
2020-03-02,765.900024,733.750000,737.000000,741.049988,9821523.0,741.049988,,,-86.547427
2020-03-04,761.500000,745.549988,753.900024,758.750000,11012895.0,758.750000,,,-83.274482

In [23]:
from portfoliotools.screener.stock_fundamentals import StockFundamentals

In [24]:
stock_fund = StockFundamentals("WIPRO")
stock_fund.get_details_info()

ERROR:root:'EBITDA'
ERROR:root:Error calculating derived info WIPRO

{}

In [25]:
stock_fund.get_balance_sheet_info()

{}

In [2]:
import screener

In [15]:
stock_fund.suffix

''

In [2]:
%pip install nsetools

Collecting nsetools
  Downloading https://files.pythonhosted.org/packages/f5/b3/6aac4226a927d5f23f154c06de7c100361e9fa07e932cd76aaa8c45a2af4/nsetools-1.0.11-py3-none-any.whl
Collecting dateutils (from nsetools)
  Downloading https://files.pythonhosted.org/packages/9d/cd/50844be53eac7e0a4d3a8e4f22a64e90c65ad9fa7d06dc5de55503d4486c/dateutils-0.6.7.tar.gz
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from nsetools) (1.12.0)
Collecting argparse (from dateutils->nsetools)
  Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dateutils->nsetools) (2.8.0)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dateutils->nsetools) (2019.2)
Installing collected packages: argparse, dateutils, nsetools
  Running setup.py install for dateutils ... done
Successfully installed argparse-1.4.0 dateutils-0.6.7 nsetools-1.0.11
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [3]:
import nsetools as ns

In [4]:
nse = ns.Nse()

In [7]:
stkList = nse.get_stock_codes()

In [35]:
nse.stocks_csv_url

'http://www1.nseindia.com/content/equities/EQUITY_L.csv'

In [3]:
from portfoliotools.screener.utility.util import getHistoricStockPrices
import pandas as pd
stock_list = ['SBI', 'HDFC', 'INFY']
prices = pd.DataFrame()
for stock in stock_list:
    prices[stock] = getHistoricStockPrices(stock, days = 1000)['Adj Close']

prices.dropna(inplace = True)
prices

                 SBI         HDFC        INFY
Date
2017-06-27  8.827995  1592.394165  415.882782
2017-06-28  8.863993  1571.127441  414.828583
2017-06-29  8.783004  1574.213867  417.295929
2017-06-30  8.854994  1557.576416  419.695953
2017-07-03  8.899988  1564.038574  427.030762
...              ...          ...         ...
2020-03-16  8.200000  1841.750000  583.150024
2020-03-17  8.270000  1755.800049  554.950012
2020-03-18  8.000000  1622.550049  534.299988
2020-03-19  8.000000  1617.599976  545.549988
2020-03-20  7.960000  1753.949951  585.200012

[653 rows x 3 columns]

In [5]:
prices.corr()

           SBI      HDFC      INFY
SBI   1.000000  0.537418  0.187607
HDFC  0.537418  1.000000  0.788869
INFY  0.187607  0.788869  1.000000